<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Stock;
use App\Models\StockMovement;
use App\Models\DetailMovement;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsWithStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Verificar que existe un usuario admin
        $adminUser = User::whereHas('role', function ($query) {
            $query->where('name', 'Admin');
        })->first();

        if (!$adminUser) {
            $this->command->error('No se encontró un usuario admin. Ejecute primero el seeder de usuarios.');
            return;
        }

        $products = [
            [
                'name' => 'Canon c356',
                'sku' => 'Can-2375',
                'barcode' => 'CAN-2375',
                'brand' => 'Canon',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 35 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Voltaje: 220V',
                'purchase_price' => 1800.00,
                'sale_price' => 3500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Canon c350',
                'sku' => 'Can-2693',
                'barcode' => 'CAN-2693',
                'brand' => 'Canon',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 35 hojas por minuto Conectividad: Tarjeta de red / USB Formato: Oficio – A4',
                'purchase_price' => 1200.00,
                'sale_price' => 2500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Canon c5540',
                'sku' => 'Can-2815',
                'barcode' => 'CAN-2815',
                'brand' => 'Canon',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 40 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Formato: A3 – A4',
                'purchase_price' => 1900.00,
                'sale_price' => 4000.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Canon c5540_2',
                'sku' => 'Can-2080',
                'barcode' => 'CAN-2080',
                'brand' => 'Canon',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 40 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Formato: A3 – A4',
                'purchase_price' => 3000.00,
                'sale_price' => 6000.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Konica Minolta bizbuh c3350i',
                'sku' => 'Kon-3443',
                'barcode' => 'KON-3443',
                'brand' => 'Konica minolta',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 35 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Formato: Oficio – A4',
                'purchase_price' => 2000.00,
                'sale_price' => 3500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Konica minolta bizbuh c3350',
                'sku' => 'Kon-2652',
                'barcode' => 'KON-2652',
                'brand' => 'Konica minolta',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 35 hojas por minuto Conectividad: Tarjeta de red / USB Formato: Oficio – A4',
                'purchase_price' => 2000.00,
                'sale_price' => 3500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Konica minolta c224',
                'sku' => 'Kon-7714',
                'barcode' => 'KON-7714',
                'brand' => 'Konica minolta',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 22 hojas por minuto Conectividad: Tarjeta de red / USB Formato: A3 – A4',
                'purchase_price' => 2000.00,
                'sale_price' => 3500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Konica',
                'sku' => 'Kon-6700',
                'barcode' => 'KON-6700',
                'brand' => 'Konica minolta',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 40 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Formato: A3 – A4',
                'purchase_price' => 2000.00,
                'sale_price' => 3500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Konica minolta c458',
                'sku' => 'Kon-2707',
                'barcode' => 'KON-2707',
                'brand' => 'Konica minolta',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 45 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Formato: A3 – A4',
                'purchase_price' => 2500.00,
                'sale_price' => 4000.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Konica minolta c758',
                'sku' => 'Kon-5652',
                'barcode' => 'KON-5652',
                'brand' => 'Konica minolta',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 75 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Formato: A3 – A4',
                'purchase_price' => 6000.00,
                'sale_price' => 12000.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Kyocera m3655',
                'sku' => 'Kyo-2598',
                'barcode' => 'KYO-2598',
                'brand' => 'kyocera',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 55 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Voltaje: 220V',
                'purchase_price' => 1500.00,
                'sale_price' => 3500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Kyocera m2540',
                'sku' => 'Kyo-6344',
                'barcode' => 'KYO-6344',
                'brand' => 'kyocera',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 25 hojas por minuto Conectividad: Tarjeta de red / USB Voltaje: 220V',
                'purchase_price' => 1000.00,
                'sale_price' => 2500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Kyocera m3040',
                'sku' => 'Kyo-9831',
                'barcode' => 'KYO-9831',
                'brand' => 'kyocera',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 30 hojas por minuto Conectividad: Tarjeta de red / USB Voltaje: 220V',
                'purchase_price' => 900.00,
                'sale_price' => 2800.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Ricoh im600',
                'sku' => 'Ric-2982',
                'barcode' => 'RIC-2982',
                'brand' => 'Ricoh',
                'category' => 'impresoras',
                'presentation' => 'Producto importado seminuevo',
                'unidad' => 'unidad',
                'description' => 'Funciones: Copia / Imprime / Escanea Velocidad: 60 hojas por minuto Conectividad: Tarjeta de red / USB Escáner: Doble lector Voltaje: 220V',
                'purchase_price' => 2000.00,
                'sale_price' => 4500.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Toner para Fotocopiadoras Minolta Color - Negro',
                'sku' => 'Ton-5556',
                'barcode' => 'TON-5556',
                'brand' => 'Uninet',
                'category' => 'toners',
                'presentation' => 'Galón de 1 kilo',
                'unidad' => 'kg',
                'description' => 'Tóner en polvo para fotocopiadoras Minolta a color (Negro).',
                'purchase_price' => 90.00,
                'sale_price' => 170.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Toner para Fotocopiadoras Minolta Color - Cyan',
                'sku' => 'Ton-7575',
                'barcode' => 'TON-7575',
                'brand' => 'Uninet',
                'category' => 'toners',
                'presentation' => 'Galón de 1 kilo',
                'unidad' => 'kg',
                'description' => 'Tóner en polvo para fotocopiadoras Minolta a color (Cyan).',
                'purchase_price' => 125.00,
                'sale_price' => 170.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Toner para Fotocopiadoras Kyocera',
                'sku' => 'Ton-8637',
                'barcode' => 'TON-8637',
                'brand' => 'Uninet',
                'category' => 'toners',
                'presentation' => 'Galón de 1 kilo',
                'unidad' => 'kg',
                'description' => 'Tóner en polvo para fotocopiadoras Kyocera.',
                'purchase_price' => 90.00,
                'sale_price' => 250.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Toner para Fotocopiadoras Ricoh',
                'sku' => 'Ton-7089',
                'barcode' => 'TON-7089',
                'brand' => 'Uninet',
                'category' => 'toners',
                'presentation' => 'Galón de 1 kilo',
                'unidad' => 'kg',
                'description' => 'Tóner en polvo para fotocopiadoras Ricoh.',
                'purchase_price' => 90.00,
                'sale_price' => 250.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Toner para Fotocopiadoras Brother',
                'sku' => 'Ton-2803',
                'barcode' => 'TON-2803',
                'brand' => 'Uninet',
                'category' => 'toners',
                'presentation' => 'Galón de 1 kilo',
                'unidad' => 'kg',
                'description' => 'Tóner en polvo para fotocopiadoras Brother.',
                'purchase_price' => 90.00,
                'sale_price' => 250.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Toner para Fotocopiadora Lexmark MX711',
                'sku' => 'Ton-4744',
                'barcode' => 'TON-4744',
                'brand' => 'Uninet',
                'category' => 'toners',
                'presentation' => 'Galón de 1 kilo',
                'unidad' => 'kg',
                'description' => 'Tóner en polvo para fotocopiadora Lexmark modelo MX711.',
                'purchase_price' => 90.00,
                'sale_price' => 250.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Cartucho de Toner para Konica Minolta C458 (Color)',
                'sku' => 'Car-6489',
                'barcode' => 'CAR-6489',
                'brand' => 'Densitoner',
                'category' => 'toners',
                'presentation' => 'Cartucho',
                'unidad' => 'unidad',
                'description' => 'Cartucho de tóner a color para fotocopiadora Konica Minolta modelo C458.',
                'purchase_price' => 125.00,
                'sale_price' => 220.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Cartucho de Toner para Canon Serie C5240',
                'sku' => 'Car-6763',
                'barcode' => 'CAR-6763',
                'brand' => 'Densitoner',
                'category' => 'toners',
                'presentation' => 'Cartucho',
                'unidad' => 'unidad',
                'description' => 'Cartucho de tóner para fotocopiadora Canon serie C5240.',
                'purchase_price' => 125.00,
                'sale_price' => 220.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Cartucho de Toner para Canon C250',
                'sku' => 'Car-3063',
                'barcode' => 'CAR-3063',
                'brand' => 'Densitoner',
                'category' => 'toners',
                'presentation' => 'Cartucho',
                'unidad' => 'unidad',
                'description' => 'Cartucho de tóner para fotocopiadoras Canon modelo C250.',
                'purchase_price' => 125.00,
                'sale_price' => 220.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Cartucho de Toner para Canon C5540',
                'sku' => 'Car-3311',
                'barcode' => 'CAR-3311',
                'brand' => 'Densitoner',
                'category' => 'toners',
                'presentation' => 'Cartucho',
                'unidad' => 'unidad',
                'description' => 'Cartucho de tóner para fotocopiadoras Canon modelo C5540.',
                'purchase_price' => 125.00,
                'sale_price' => 220.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Tinta para Impresoras Epson y Brother',
                'sku' => 'Tin-5963',
                'barcode' => 'TIN-5963',
                'brand' => 'Uninet',
                'category' => 'tintas',
                'presentation' => 'Galón de 1 litro',
                'unidad' => 'l',
                'description' => 'Tinta para impresoras Epson y Brother.',
                'purchase_price' => 35.00,
                'sale_price' => 80.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Tinta para Impresoras Brother y Plotters',
                'sku' => 'Tin-8275',
                'barcode' => 'TIN-8275',
                'brand' => 'Uninet',
                'category' => 'tintas',
                'presentation' => 'Galón de 1 litro',
                'unidad' => 'l',
                'description' => 'Tinta para impresoras Brother y equipos tipo plotter.',
                'purchase_price' => 30.00,
                'sale_price' => 80.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
            [
                'name' => 'Tinta para Impresoras Canon',
                'sku' => 'Tin-4797',
                'barcode' => 'TIN-4797',
                'brand' => 'Uninet',
                'category' => 'tintas',
                'presentation' => 'Galón de 1 litro',
                'unidad' => 'l',
                'description' => 'Tinta para impresoras Canon.',
                'purchase_price' => 30.00,
                'sale_price' => 90.00,
                'initial_quantity' => 2,
                'min_stock' => 1,
            ],
        ];

        DB::transaction(function () use ($products, $adminUser) {
            $this->command->info('Creando productos y stock...');
            
            $stockMovement = StockMovement::create([
                'movement_type' => 'entrada',
                'reason' => 'Inventario inicial - Carga de productos del catálogo',
                'voucher_number' => 'INV-INICIAL-' . date('YmdHis'),
                'user_id' => $adminUser->id,
            ]);

            foreach ($products as $productData) {
                // Crear producto
                $product = Product::create([
                    'name' => $productData['name'],
                    'sku' => $productData['sku'],
                    'image_url' => '',
                    'barcode' => $productData['barcode'],
                    'brand' => $productData['brand'],
                    'category' => $productData['category'],
                    'presentation' => $productData['presentation'],
                    'unidad' => $productData['unidad'],
                    'description' => $productData['description'],
                    'user_id' => $adminUser->id,
                ]);

                // Crear stock para el producto
                $stock = Stock::create([
                    'product_id' => $product->id,
                    'quantity' => $productData['initial_quantity'],
                    'min_stock' => $productData['min_stock'],
                    'max_stock' => $productData['initial_quantity'] * 5, // 5 veces la cantidad inicial
                    'purchase_price' => $productData['purchase_price'],
                    'sale_price' => $productData['sale_price'],
                ]);

                // Crear detalle del movimiento de stock
                DetailMovement::create([
                    'stock_movement_id' => $stockMovement->id,
                    'stock_id' => $stock->id,
                    'quantity' => $productData['initial_quantity'],
                    'unit_price' => $productData['purchase_price'],
                    'previous_stock' => 0,
                    'new_stock' => $productData['initial_quantity'],
                ]);

                $this->command->info("✓ Producto creado: {$product->name} (Stock: {$productData['initial_quantity']})");
            }

            $this->command->info('✅ Todos los productos han sido creados con éxito!');
            $this->command->info("📦 Movimiento de stock creado: #{$stockMovement->id}");
            $this->command->info("📊 Total de productos: " . count($products));
        });
    }
}