services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mastercolorapi
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - redis
    networks:
      - mastercolorapi_network

  redis:
    image: redis:7-alpine
    container_name: mastercolorapi_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - almazen_network

volumes:
  redis_data:

networks:
  almazen_network:
    driver: bridge
